:feelpp: Feel++
:cpp: C++
:project: csmi-prepost 

= CSMI Pre and Post Processing
Christophe Trophime <https://github.com/Trophime[@Trophime]>
Jonathan Sarton  <https://github.com/joSarton[@joSarton]>
v2: 

image:https://github.com/feelpp/course-project-dash/workflows/CI/badge.svg[CI]

This repository contains the source of CSMI Pre and PostProcessing course.
It includes:

- [x] documentation using asciidoc and antora
- [x] {feelpp} applications in {cpp} to use {feelpp} and {feelpp} toolboxes in `src`
- [x] python {feelpp} notebooks that can be downloaded from the documentation
- [x] continuous integration including tests for the {cpp} applications
- [x] docker image generation for the course

The documentation for csmi-prepost is available at link:https://trophime.github.io/CSMI-PrePost/course-project-dash/[here] and you can build on it for your project by enabling the link:https://docs.github.com/en/pages[github pages] for your repository.

== Setting up CI/CD

 - create an empty .nojekyll in gh-pages
 - in repository settings, add secrets attached to the repository

== Developing docs

 - open the project in `vscode`
 - stats the devcontainer
 - run `./antora-preview.sh`
 - start Vscode Liveserver extension 
 
== Updating the {project} version

The version of the project is defined in the files `CMakeLists.txt`, `docs/antora.yml` and `docs/package.json`. 
You need to update with the same version in all files.

== Release process

- [x] update the version in CMakeLists.txt
- [x] update the version in docs/antora.yml
- [x] commit the changes with the message "Release vx.y.z". At this point the CI will generate the docker image and push it to docker hub
