site:
  title: PrePost Processing for Scientific Computing
  url: https://trophime.github.io/course.prepost/
  start_page: course-prepost::index.adoc
content:
  sources:
  - url: .
    branches: HEAD
    start_path: docs
ui:
  supplemental_files: 
    - path: ./docs/antora/supplemental-ui
    - path: .nojekyll
  bundle:
    url: https://github.com/Trophime/feelpp-antora-ui/releases/download/v0.2/ui-bundle.zip
    snapshot: true
output:
  clean: true
  dir: public
antora:
  extensions:
  - '@antora/collector-extension'
asciidoc:
  attributes:
    uri-github: https://github.com/
    uri-org-feelpp: https://github.com/feelpp/
    uri-github-feelpp: https://github.com/feelpp/feelpp/
    uri-github-feelpp-raw: https://raw.githubusercontent.com/feelpp/feelpp
    uri-gmsh-www: https://gmsh.info
    uri-gmsh-manual: https://gmsh.info/doc/texinfo/gmsh.html
    uri-benchmarks: https://docs.feelpp.org/toolboxes/latest/index.html
    uri-salome-www: https://www.salome-platform.org/
    uri-freecad-www: https://www.freecad.org/
    uri-openscad-www: https://openscad.org/index.html
    uri-cgal-www: https://www.cgal.org/
    uri-mmg3d-www: http://www.mmgtools.org/
    uri-docker-www: https://www.docker.com/
    uri-apptainer-www: https://apptainer.org/
    uri-singularity-www: https://sylabs.io/singularity/
    uri-paraview-www: https://paraview.org
    python: Python
    feelpp: Feel++
    feelpptb: Feel++ Toolboxes
    feelppmor: Feel++ Model Order Reduction
    pyfeelpp: pyFeel++
    pyfeelpptb: pyFeel++ Toolboxes
    pyfeelppmor: pyFeel++ MOR
    stem: latexmath
    vtkjs: Vtkjs
    matplotlib: matplotlib
    pyvista: PyVista
    ensight: Ensight
    plotly: Plot.ly
    meshgems: MeshGems
    salome: Salome
    freecad: FreeCad
    openscad: OpenScad
    occ: OpenCascade
    cgal: Cgal
    mmg3d: mmgtools
    gmsh: Gmsh
    mmg: MmgTools
    netgen: netgen
    tetgen: tetgen
    docker: Docker
    apptainer: Apptainer
    singularity: Singularity
    sregistry: Sregistry
    jupyter: Jupyter
    paraview: ParaView
    paraview-website: link:{uri-paraview-www}[{paraview}]
    vtk: Vtk
    cpp: C++
    cpp14: C++14
    cmake: CMake
    vscode: VScode
    girder: Girder
    plantuml-server-url: http://www.plantuml.com/plantuml  
  extensions:
  - '@feelpp/asciidoctor-extensions'
