= Gmsh Environment

Gmsh is an open source 3D finite element mesh generator with a built-in CAD engine and post-processor.
We use it to generate the geometry and mesh in {feelpp}.

== Get {gmsh}

For this course, we use in addition Gmsh Python API to automatically create CAD and mesh.
To install the Python bindings, you can use the python3-gmsh package from your distribution.

[source,shell]
----
 $ [sudo] apt update
 $ [sudo] apt install python3-gmsh
----

However, we recommend to use a virtual python env to install a more recent version of {gmsh}:

[source,shell]
----
 $ $ python3 -m venv [--system-site-packages] gmsh-env # <1>
 $ source ./gmsh-env/bin/activate #
 $ python3 -m pip install gmsh #
----

[NOTE]
====
On Windows:
[source,shell]
----
c:\>C:\Python35\python -m venv c:\path\to\gmsh-env
C:\> C:\path\to\gmsh-env\Scripts\activate.bat
c:\>C:\Python35\python -m pip install gmsh
----
====

We recommend to edit {gmsh} `geo` files with {vscode}.
To get syntax highlighting for these files, install https://marketplace.visualstudio.com/items?itemName=Bertrand-Thierry.vscode-gmsh [vscode-gmsh extension].

== Camera

with a mouse:

[cols="1,1"]
|===
| Operation	| Result 

| left click | Rotation 

| right click | Translation  

| wheel	| Zoom 
|===


with a trackpad:

[cols="1,1"]
|===
| Operation	  | Result 

| left click  |	Rotation 

| right click |	Translation 

| multi-finger	      | Zoom 
|===

[NOTE]
====
Scrolling on trackpad may require some additional settings to work properly.
See your trackpad configuration.
====

== References

* https://gmsh.info/#Documentation[Official {gmsh} documentation]
* Python API: https://gmsh.info/doc/texinfo/gmsh.html#Gmsh-application-programming-interface[documentation] and https://gitlab.onelab.info/gmsh/gmsh/-/tree/master/tutorials?ref_type=heads[examples]
* https://bthierry.pages.math.cnrs.fr/tutorial/gmsh/[A Tutorial] from B. Thierry. 